Build persistent x86 installer ISO with disk expansion

diff --git a/.github/workflows/X86-v3.yml b/.github/workflows/X86-v3.yml
--- a/.github/workflows/X86-v3.yml
+++ b/.github/workflows/X86-v3.yml
@@ -39,7 +39,7 @@ jobs:
           sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* snap* || true
           sudo -E apt update
           sudo -E apt full-upgrade -y
-          sudo -E apt -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
+          sudo -E apt -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xorriso xxd zlib1g-dev
           sudo -E apt -y autoremove --purge
           sudo -E apt clean
           df -h
@@ -75,6 +75,11 @@ jobs:
           CONFIG_TARGET_x86_64_DEVICE_generic=y
           CONFIG_TARGET_IMAGES_GZIP=y
           CONFIG_TARGET_ROOTFS_SQUASHFS=y
+          CONFIG_TARGET_ROOTFS_EXT4FS=y
+          CONFIG_TARGET_ROOTFS_PARTSIZE=1024
+          CONFIG_GRUB_IMAGES=y
+          CONFIG_GRUB_EFI_IMAGES=y
+          CONFIG_ISO_IMAGES=y
           CONFIG_VMDK_IMAGES=y
 
           # 基础工具
@@ -133,6 +138,13 @@ jobs:
           CONFIG_PACKAGE_nftables-nojson=y
           CONFIG_PACKAGE_kmod-nft-bridge=y
 
+          # 安装 ISO：磁盘分区和 ext4 根文件系统扩容工具
+          CONFIG_PACKAGE_lsblk=y
+          CONFIG_PACKAGE_parted=y
+          CONFIG_PACKAGE_sgdisk=y
+          CONFIG_PACKAGE_e2fsprogs=y
+          CONFIG_PACKAGE_resize2fs=y
+
           # 初期验证透明代理时不使用 TurboACC 自动配置加速
           # CONFIG_PACKAGE_luci-app-turboacc is not set
 
@@ -154,10 +166,18 @@ jobs:
           #
           sed -i 's/^[ \t]*//g' ./.config
           make defconfig
-          grep -qx 'CONFIG_VMDK_IMAGES=y' .config || {
-            echo '::error::VMDK image support was dropped by make defconfig'
-            exit 1
-          }
+          for option in VMDK_IMAGES ISO_IMAGES GRUB_IMAGES GRUB_EFI_IMAGES TARGET_ROOTFS_EXT4FS; do
+            grep -qx "CONFIG_${option}=y" .config || {
+              echo "::error::Required image option missing after make defconfig: CONFIG_${option}=y"
+              exit 1
+            }
+          done
+
+      - name: Stage installer in root filesystem
+        run: |
+          mkdir -p files/usr/sbin files/etc/profile.d
+          install -m 0755 .github/scripts/x86-iso-install.sh files/usr/sbin/lede-install
+          install -m 0644 .github/scripts/x86-iso-profile.sh files/etc/profile.d/99-lede-installer.sh
 
       - name: Save configuration before verification
         run: |
@@ -203,6 +223,11 @@ jobs:
             PACKAGE_kmod-ebtables-ipv6 \
             PACKAGE_nftables-nojson \
             PACKAGE_kmod-nft-bridge \
+            PACKAGE_lsblk \
+            PACKAGE_parted \
+            PACKAGE_sgdisk \
+            PACKAGE_e2fsprogs \
+            PACKAGE_resize2fs \
             PACKAGE_ipset \
             PACKAGE_dnsmasq-full \
             PACKAGE_dnsmasq_full_ipset; do
@@ -255,6 +280,29 @@ jobs:
           du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
           du -h --max-depth=1 ./build_dir
           du -h --max-depth=1 ./bin
+
+      - name: Package bootable installer ISO
+        run: |
+          shopt -s nullglob
+          target=./bin/targets/x86/64
+          iso=("$target"/*-image-efi.iso)
+          bios=("$target"/*-ext4-combined.img.gz)
+          efi=("$target"/*-ext4-combined-efi.img.gz)
+          if (( ${#iso[@]} != 1 || ${#bios[@]} != 1 || ${#efi[@]} != 1 )); then
+            echo '::error::Expected one EFI ISO and both ext4 disk images'
+            exit 1
+          fi
+          mkdir -p installer-images
+          cp "${bios[0]}" installer-images/bios.img.gz
+          cp "${efi[0]}" installer-images/efi.img.gz
+          gzip -dc installer-images/bios.img.gz | wc -c | tr -d ' ' > installer-images/bios.bytes
+          gzip -dc installer-images/efi.img.gz | wc -c | tr -d ' ' > installer-images/efi.bytes
+          (cd installer-images && sha256sum bios.img.gz efi.img.gz > SHA256SUMS)
+          installer_iso="${iso[0]%-image-efi.iso}-installer.iso"
+          xorriso -indev "${iso[0]}" -outdev "$installer_iso" \
+            -map ./installer-images /installer -boot_image any replay
+          test -s "$installer_iso"
+          echo "Installer ISO: $installer_iso"
 
       - name: Prepare artifact
         run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf
